<a href="https://colab.research.google.com/github/mesh1992/Artificial-Intelligence-with-Python/blob/master/Q6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Q6
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print("\n")
print(matrix.T)


[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]
